# Generated by Django 5.2.7 on 2025-11-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='input_audio_url',
            field=models.URLField(blank=True, help_text='URL of input audio file', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='input_image_url',
            field=models.URLField(blank=True, help_text='URL of input image (before processing)', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='input_video_url',
            field=models.URLField(blank=True, help_text='URL of input video (uploaded or external link)', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='output_audio_url',
            field=models.URLField(blank=True, help_text='URL of output audio file', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='output_image_url',
            field=models.URLField(blank=True, help_text='URL of output image (after processing)', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='output_video_url',
            field=models.URLField(blank=True, help_text='URL of output video (after processing)', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='prompt',
            field=models.TextField(blank=True, help_text='Example prompt to demonstrate how the tool works'),
        ),
        migrations.AddField(
            model_name='tool',
            name='result',
            field=models.TextField(blank=True, help_text='Description of the expected output or result'),
        ),
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.CharField(blank=True, choices=[('text-to-image', 'Text to Image'), ('text-to-video', 'Text to Video'), ('text-to-audio', 'Text to Audio'), ('image-to-image', 'Image to Image'), ('image-to-video', 'Image to Video'), ('video-to-video', 'Video to Video'), ('audio-to-audio', 'Audio to Audio'), ('text-to-text', 'Text to Text'), ('other', 'Other')], help_text='Type of AI tool (e.g., text-to-image, image-to-image)', max_length=100),
        ),
    ]
