# Generated by Django 5.2.7 on 2025-11-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tool_input_audio_url_tool_input_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Writing', 'Writing Tools'), ('Design', 'Design & Graphics'), ('Presentation', 'Presentation Tools'), ('Productivity', 'Productivity & Organization'), ('Image Generation', 'Image Generation'), ('Video Editing', 'Video Editing'), ('Code Assistant', 'Code Assistant'), ('Voice & Audio', 'Voice & Audio'), ('Research', 'Research & Analysis'), ('Marketing', 'Marketing & Social Media'), ('Data Analysis', 'Data Analysis'), ('Education', 'Education & Learning'), ('Business', 'Business & Finance'), ('Music & Audio', 'Music & Audio'), ('3D & Animation', '3D & Animation'), ('Translation', 'Translation & Localization'), ('Customer Service', 'Customer Service'), ('Content Creation', 'Content Creation'), ('Other', 'Other')], help_text='Select the primary category for this AI tool', max_length=100),
        ),
    ]
