# Generated by Django 5.2.7 on 2025-11-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tool_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToolExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('result_text', models.TextField(blank=True, null=True)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='examples/')),
            ],
        ),
        migrations.CreateModel(
            name='UsageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='brand_color',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='editor_score',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='input_audio_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='input_image_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='input_video_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='key_features',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='output_audio_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='output_image_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='output_video_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='result',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='review',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='use_cases',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='users',
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Writing', 'Writing Tools'), ('Design', 'Design & Graphics'), ('Presentation', 'Presentation Tools'), ('Productivity', 'Productivity & Organization'), ('Image Generation', 'Image Generation'), ('Video Editing', 'Video Editing'), ('Code Assistant', 'Code Assistant'), ('Voice & Audio', 'Voice & Audio'), ('Research', 'Research & Analysis'), ('Marketing', 'Marketing & Social Media'), ('Data Analysis', 'Data Analysis'), ('Education', 'Education & Learning'), ('Business', 'Business & Finance'), ('Music & Audio', 'Music & Audio'), ('3D & Animation', '3D & Animation'), ('Translation', 'Translation & Localization'), ('Customer Service', 'Customer Service'), ('Content Creation', 'Content Creation'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('text-to-text', 'Text to Text'), ('text-to-image', 'Text to Image'), ('text-to-video', 'Text to Video'), ('text-to-audio', 'Text to Audio'), ('image-to-image', 'Image to Image'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='usage_guide',
            field=models.TextField(blank=True, help_text="Add overall usage instructions or leave blank if you use 'Usage Steps' below."),
        ),
        migrations.AddField(
            model_name='con',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons', to='api.tool'),
        ),
        migrations.AddField(
            model_name='keyfeature',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='api.tool'),
        ),
        migrations.AddField(
            model_name='pro',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='api.tool'),
        ),
        migrations.AddField(
            model_name='toolexample',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='api.tool'),
        ),
        migrations.AddField(
            model_name='usagestep',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_steps', to='api.tool'),
        ),
    ]
