# Generated by Django 5.2.7 on 2025-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_con_keyfeature_pro_toolexample_usagestep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('author_avatar', models.URLField(blank=True, null=True)),
                ('author_bio', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('AI Tools', 'AI Tools'), ('Tutorials', 'Tutorials'), ('Reviews', 'Reviews'), ('Updates', 'Updates'), ('Case Studies', 'Case Studies'), ('Productivity', 'Productivity'), ('Education', 'Education')], max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('views', models.IntegerField(default=0)),
                ('read_time', models.IntegerField(blank=True, help_text='Reading time in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('Product Launch', 'Product Launch'), ('Feature Update', 'Feature Update'), ('Industry News', 'Industry News'), ('Company Announcement', 'Company Announcement'), ('Research', 'Research'), ('Events', 'Events')], max_length=100)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='con',
            options={'verbose_name': 'Con', 'verbose_name_plural': 'Cons'},
        ),
        migrations.AlterModelOptions(
            name='keyfeature',
            options={'verbose_name': 'Key Feature', 'verbose_name_plural': 'Key Features'},
        ),
        migrations.AlterModelOptions(
            name='pro',
            options={'verbose_name': 'Pro', 'verbose_name_plural': 'Pros'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Tool', 'verbose_name_plural': 'AI Tools'},
        ),
        migrations.AlterModelOptions(
            name='usagestep',
            options={'verbose_name': 'Usage Step', 'verbose_name_plural': 'Usage Steps'},
        ),
        migrations.AddField(
            model_name='tool',
            name='prompt',
            field=models.TextField(blank=True, help_text='Example input/prompt for this tool'),
        ),
        migrations.AddField(
            model_name='tool',
            name='result_image',
            field=models.ImageField(blank=True, help_text='Example image output', null=True, upload_to='tool_results/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='result_text',
            field=models.TextField(blank=True, help_text='Example text output', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='usage_guide',
            field=models.TextField(blank=True, help_text='Add overall usage instructions'),
        ),
        migrations.DeleteModel(
            name='ToolExample',
        ),
    ]
