# Generated by Django 5.2.7 on 2025-11-06 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tool_prompt_image_tool_result_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='usage_guide',
            field=models.TextField(blank=True, help_text='Add overall usage instructions (supports markdown)'),
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Use case title (e.g., 'Product Description Generator')", max_length=255)),
                ('description', models.TextField(help_text='Detailed description of this use case')),
                ('type', models.CharField(help_text="Type matching the tool's AI type (e.g., 'text-to-image', 'text-generation')", max_length=50)),
                ('prompt', models.TextField(blank=True, help_text='Example prompt or input text')),
                ('result', models.TextField(blank=True, help_text='Expected result or output description')),
                ('input_image_url', models.URLField(blank=True, help_text='URL to input image (before processing)', null=True)),
                ('input_video_url', models.URLField(blank=True, help_text='URL to input video (YouTube, Vimeo, or direct MP4)', null=True)),
                ('input_audio_url', models.URLField(blank=True, help_text='URL to input audio (MP3 or direct link)', null=True)),
                ('output_image_url', models.URLField(blank=True, help_text='URL to output image (after processing)', null=True)),
                ('output_video_url', models.URLField(blank=True, help_text='URL to output video (YouTube, Vimeo, or direct MP4)', null=True)),
                ('output_audio_url', models.URLField(blank=True, help_text='URL to output audio (MP3 or direct link)', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='api.tool')),
            ],
            options={
                'verbose_name': 'Use Case',
                'verbose_name_plural': 'Use Cases',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
