# Generated by Django 5.2.7 on 2025-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tool_usage_guide_usecase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='usage_guide',
            field=models.TextField(blank=True, help_text='Add overall usage instructions'),
        ),
        migrations.DeleteModel(
            name='UseCase',
        ),
    ]
