# Generated by Django 5.2.7 on 2025-11-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tool_usage_guide_delete_usecase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagestep',
            options={'verbose_name': 'Usage Step', 'verbose_name_plural': 'Usage Guide Steps'},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='usage_guide',
        ),
        migrations.AlterField(
            model_name='tool',
            name='overview',
            field=models.TextField(blank=True, help_text='Short overview of how the tool works'),
        ),
    ]
