# Generated by Django 5.2.7 on 2025-11-06 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usagestep_options_remove_tool_usage_guide_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='con',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keyfeature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usagestep',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='author',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='author',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.RemoveField(
            model_name='author',
            name='personal_website',
        ),
        migrations.RemoveField(
            model_name='author',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_avatar',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_bio',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='external_url',
        ),
        migrations.AddField(
            model_name='tool',
            name='usage_guide',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='difficulty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='tool_featured/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='pricing',
            field=models.CharField(choices=[('Free', 'Free'), ('Freemium', 'Freemium'), ('Paid', 'Paid')], default='Free', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='result_audio_url',
            field=models.URLField(blank=True, help_text='Example audio output URL', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='result_video_url',
            field=models.URLField(blank=True, help_text='Example video output URL', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('Text-to-Text', 'Text-to-Text'), ('Text-to-Image', 'Text-to-Image'), ('Image-to-Image', 'Image-to-Image'), ('Image-to-Video', 'Image-to-Video'), ('Text-to-Audio', 'Text-to-Audio'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usagestep',
            name='step',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ToolDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, help_text='Example text input or prompt')),
                ('prompt_image', models.ImageField(blank=True, help_text='Example input image (for image-to-image, etc.)', null=True, upload_to='tool_prompts/')),
                ('result_text', models.TextField(blank=True, help_text='Example text output', null=True)),
                ('result_image', models.ImageField(blank=True, help_text='Example image output', null=True, upload_to='tool_results/')),
                ('result_video_url', models.URLField(blank=True, help_text='Example video output URL', null=True)),
                ('result_audio_url', models.URLField(blank=True, help_text='Example audio output URL', null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demos', to='api.tool')),
            ],
        ),
    ]
