# Generated by Django 5.2.7 on 2025-11-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_author_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='con',
            options={'verbose_name': 'Con', 'verbose_name_plural': 'Cons'},
        ),
        migrations.AlterModelOptions(
            name='keyfeature',
            options={'verbose_name': 'Key Feature', 'verbose_name_plural': 'Key Features'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'News Item', 'verbose_name_plural': 'News Items'},
        ),
        migrations.AlterModelOptions(
            name='pro',
            options={'verbose_name': 'Pro', 'verbose_name_plural': 'Pros'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Tool', 'verbose_name_plural': 'AI Tools'},
        ),
        migrations.AlterModelOptions(
            name='usagestep',
            options={'verbose_name': 'Usage Step', 'verbose_name_plural': 'Usage Guide Steps'},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='usage_guide',
        ),
        migrations.AddField(
            model_name='author',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('AI Tools', 'AI Tools'), ('Tutorials', 'Tutorials'), ('Reviews', 'Reviews'), ('Updates', 'Updates'), ('Case Studies', 'Case Studies'), ('Productivity', 'Productivity'), ('Education', 'Education')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.IntegerField(blank=True, help_text='Reading time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Product Launch', 'Product Launch'), ('Feature Update', 'Feature Update'), ('Industry News', 'Industry News'), ('Company Announcement', 'Company Announcement'), ('Research', 'Research'), ('Events', 'Events')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Writing', 'Writing Tools'), ('Design', 'Design & Graphics'), ('Presentation', 'Presentation Tools'), ('Productivity', 'Productivity & Organization'), ('Image Generation', 'Image Generation'), ('Video Editing', 'Video Editing'), ('Code Assistant', 'Code Assistant'), ('Voice & Audio', 'Voice & Audio'), ('Research', 'Research & Analysis'), ('Marketing', 'Marketing & Social Media'), ('Data Analysis', 'Data Analysis'), ('Education', 'Education & Learning'), ('Business', 'Business & Finance'), ('Music & Audio', 'Music & Audio'), ('3D & Animation', '3D & Animation'), ('Translation', 'Translation & Localization'), ('Customer Service', 'Customer Service'), ('Content Creation', 'Content Creation'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='tools/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='overview',
            field=models.TextField(blank=True, help_text='Short overview of how the tool works'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='pricing',
            field=models.CharField(choices=[('Free', 'Free'), ('Freemium', 'Freemium'), ('Paid', 'Paid'), ('Enterprise', 'Enterprise')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='result_audio_url',
            field=models.URLField(blank=True, help_text='Example audio output URL (SoundCloud, direct MP3, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='result_video_url',
            field=models.URLField(blank=True, help_text='Example video output URL (YouTube, Vimeo, direct MP4, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('text-to-text', 'Text to Text'), ('text-to-image', 'Text to Image'), ('text-to-video', 'Text to Video'), ('text-to-audio', 'Text to Audio'), ('image-to-image', 'Image to Image'), ('image-to-video', 'Image to Video'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usagestep',
            name='step',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ToolDemo',
        ),
    ]
