# Generated by Django 5.2.7 on 2025-11-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_author_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='prompt_image',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='result_audio_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='result_image',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='result_text',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='result_video_url',
        ),
        migrations.CreateModel(
            name='DemoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, help_text='Example input or prompt')),
                ('result_text', models.TextField(blank=True, help_text='Example text output', null=True)),
                ('result_image', models.ImageField(blank=True, help_text='Example image output', null=True, upload_to='tool_results/')),
                ('result_video_url', models.URLField(blank=True, help_text='Example video output URL (YouTube, Vimeo, direct MP4, etc.)', null=True)),
                ('result_audio_url', models.URLField(blank=True, help_text='Example audio output URL (SoundCloud, direct MP3, etc.)', null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_examples', to='api.tool')),
            ],
            options={
                'verbose_name': 'Demo Example',
                'verbose_name_plural': 'Demo Examples',
            },
        ),
    ]
