# Generated by Django 5.2.7 on 2025-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_tool_prompt_remove_tool_prompt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoexample',
            name='prompt_image',
            field=models.ImageField(blank=True, help_text='Example input image (used for image-to-image or image-to-video tools)', null=True, upload_to='tool_prompts/'),
        ),
        migrations.AlterField(
            model_name='demoexample',
            name='prompt',
            field=models.TextField(blank=True, help_text='Example input or prompt (text-based)'),
        ),
    ]
