# Generated by Django 5.2.7 on 2025-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_demoexample_prompt_image_alter_demoexample_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoexample',
            name='prompt_image',
        ),
        migrations.AlterField(
            model_name='demoexample',
            name='prompt',
            field=models.TextField(blank=True, help_text='Example input or prompt'),
        ),
    ]
