# Generated by Django 5.2.7 on 2025-11-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tool_prompt_tool_prompt_image_tool_result_audio_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='prompt_image',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='result_audio_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='result_image',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='result_text',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='result_video_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='type',
        ),
        migrations.CreateModel(
            name='ToolDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_type', models.CharField(choices=[('text-to-text', 'Text to Text'), ('text-to-image', 'Text to Image'), ('text-to-video', 'Text to Video'), ('text-to-audio', 'Text to Audio'), ('image-to-image', 'Image to Image'), ('image-to-video', 'Image to Video'), ('image-to-text', 'Image to Text'), ('audio-to-text', 'Audio to Text'), ('video-to-text', 'Video to Text'), ('multi-modal', 'Multi-modal (Multiple Inputs)'), ('other', 'Other')], max_length=100)),
                ('title', models.CharField(help_text="e.g., 'Creative Writing', 'Code Generation'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this demo shows')),
                ('input_prompt', models.TextField(blank=True, help_text='Example text input/prompt for this demo')),
                ('input_image_file', models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='demo_inputs/')),
                ('input_image_url', models.URLField(blank=True, help_text='Or provide a URL to an image (e.g., from Google Drive, Imgur, etc.)', null=True)),
                ('input_audio_file', models.FileField(blank=True, help_text='Upload an audio file (MP3, WAV, etc.)', null=True, upload_to='demo_inputs/audio/')),
                ('input_audio_url', models.URLField(blank=True, help_text='Or provide a URL to audio', null=True)),
                ('input_video_file', models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, etc.)', null=True, upload_to='demo_inputs/video/')),
                ('input_video_url', models.URLField(blank=True, help_text='Or provide a URL to a video', null=True)),
                ('output_text', models.TextField(blank=True, help_text='Example text output', null=True)),
                ('output_image_file', models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='demo_outputs/')),
                ('output_image_url', models.URLField(blank=True, help_text='Or provide a URL to an image', null=True)),
                ('output_audio_file', models.FileField(blank=True, help_text='Upload an audio file', null=True, upload_to='demo_outputs/audio/')),
                ('output_audio_url', models.URLField(blank=True, help_text='Or provide a URL to audio', null=True)),
                ('output_video_file', models.FileField(blank=True, help_text='Upload a video file', null=True, upload_to='demo_outputs/video/')),
                ('output_video_url', models.URLField(blank=True, help_text='Or provide a URL to a video (YouTube, Vimeo, direct MP4, etc.)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demos', to='api.tool')),
            ],
            options={
                'verbose_name': 'Tool Demo',
                'verbose_name_plural': 'Tool Demos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
