# Generated by Django 5.2.7 on 2025-11-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_tool_prompt_remove_tool_prompt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_ge',
            field=models.TextField(blank=True, verbose_name='Bio (Georgian)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_bio_ge',
            field=models.TextField(blank=True, verbose_name='Author Bio (Georgian)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ge',
            field=models.TextField(blank=True, verbose_name='Content (Georgian)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ge',
            field=models.TextField(blank=True, max_length=500, verbose_name='Excerpt (Georgian)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ge',
            field=models.CharField(blank=True, max_length=300, verbose_name='Title (Georgian)'),
        ),
        migrations.AddField(
            model_name='con',
            name='text_ge',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text (Georgian)'),
        ),
        migrations.AddField(
            model_name='keyfeature',
            name='feature_ge',
            field=models.CharField(blank=True, max_length=255, verbose_name='Feature (Georgian)'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary_ge',
            field=models.TextField(blank=True, max_length=500, verbose_name='Summary (Georgian)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ge',
            field=models.CharField(blank=True, max_length=300, verbose_name='Title (Georgian)'),
        ),
        migrations.AddField(
            model_name='pro',
            name='text_ge',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text (Georgian)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='description_ge',
            field=models.TextField(blank=True, verbose_name='Description (Georgian)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='name_ge',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Georgian)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='overview_ge',
            field=models.TextField(blank=True, verbose_name='Overview (Georgian)'),
        ),
        migrations.AddField(
            model_name='tooldemo',
            name='description_ge',
            field=models.TextField(blank=True, verbose_name='Description (Georgian)'),
        ),
        migrations.AddField(
            model_name='tooldemo',
            name='input_prompt_ge',
            field=models.TextField(blank=True, help_text='Georgian translation of the input prompt', verbose_name='Input Prompt (Georgian)'),
        ),
        migrations.AddField(
            model_name='tooldemo',
            name='output_text_ge',
            field=models.TextField(blank=True, help_text='Georgian translation of the output text', null=True, verbose_name='Output Text (Georgian)'),
        ),
        migrations.AddField(
            model_name='tooldemo',
            name='title_ge',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Georgian)'),
        ),
        migrations.AddField(
            model_name='usagestep',
            name='step_ge',
            field=models.CharField(blank=True, max_length=255, verbose_name='Step (Georgian)'),
        ),
    ]
