# Generated by Django 5.2.7 on 2025-11-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_author_bio_ge_blogpost_author_bio_ge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/content_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_ge', models.CharField(blank=True, max_length=255, verbose_name='Caption (Georgian)')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within blog post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Image',
                'verbose_name_plural': 'Blog Post Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
